[package]
name = "{{name}}"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
sha2 = "0.10"
hex = "0.4"
web-sys = { version = "0.3", features = ["Performance", "Window"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 3